  
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js: '8'
install: npm install
before_script:
  - npm prune
script:
  - npm run test:unit
branches:
  only: master