export default [
  { code: 'AFG', value: 'Afghanistan', alias: '', lemma: 'Afghanistan' },
  { code: 'ALA', value: 'Aland Islands', alias: '', lemma: 'Aland Islands' },
  { code: 'ALB', value: 'Albania', alias: '', lemma: 'Albania' },
  { code: 'DZA', value: 'Algeria', alias: '', lemma: 'Algeria' },
  { code: 'ASM', value: 'American Samoa', alias: '', lemma: 'American Samoa' },
  { code: 'AND', value: 'Andorra', alias: '', lemma: 'Andorra' },
  { code: 'AGO', value: 'Angola', alias: '', lemma: 'Angola' },
  { code: 'AIA', value: 'Anguilla', alias: '', lemma: 'Anguilla' },
  { code: 'ATA', value: 'Antarctica', alias: '', lemma: 'Antarctica' },
  {
    code: 'ATG',
    value: 'Antigua and Barbuda',
    alias: '',
    lemma: 'Antigua and Barbuda',
  },
  { code: 'ARG', value: 'Argentina', alias: '', lemma: 'Argentina' },
  {
    code: 'ARG',
    value: 'Argentina (Buenos Aires)',
    alias: 'Buenos Aires',
    lemma: 'Argentina',
  },
  {
    code: 'ARG',
    value: 'Argentina (Patagonia)',
    alias: 'Patagonia',
    lemma: 'Argentina',
  },
  { code: 'ARM', value: 'Armenia', alias: '', lemma: 'Armenia' },
  { code: 'ABW', value: 'Aruba', alias: '', lemma: 'Aruba' },
  { code: 'AUS', value: 'Australia', alias: '', lemma: 'Australia' },
  {
    code: 'AUS',
    value: 'Australia (Adelaide)',
    alias: 'Adelaide',
    lemma: 'Australia',
  },
  {
    code: 'AUS',
    value: 'Australia (Brisbane)',
    alias: 'Brisbane',
    lemma: 'Australia',
  },
  {
    code: 'AUS',
    value: 'Australia (Cairns)',
    alias: 'Cairns',
    lemma: 'Australia',
  },
  {
    code: 'AUS',
    value: 'Australia (Canberra)',
    alias: 'Canberra',
    lemma: 'Australia',
  },
  {
    code: 'AUS',
    value: 'Australia (Darwin)',
    alias: 'Darwin',
    lemma: 'Australia',
  },
  {
    code: 'AUS',
    value: 'Australia (Hamilton Island)',
    alias: 'Hamilton Island',
    lemma: 'Australia',
  },
  {
    code: 'AUS',
    value: 'Australia (Melbourne)',
    alias: 'Melbourne',
    lemma: 'Australia',
  },
  {
    code: 'AUS',
    value: 'Australia (Norfolk Island)',
    alias: 'Norfolk Island',
    lemma: 'Australia',
  },
  {
    code: 'AUS',
    value: 'Australia (Perth)',
    alias: 'Perth',
    lemma: 'Australia',
  },
  {
    code: 'AUS',
    value: 'Australia (Queensland)',
    alias: 'Queensland',
    lemma: 'Australia',
  },
  {
    code: 'AUS',
    value: 'Australia (Sydney)',
    alias: 'Sydney',
    lemma: 'Australia',
  },
  {
    code: 'AUS',
    value: 'Australia (Tasmania)',
    alias: 'Tasmania',
    lemma: 'Australia',
  },
  { code: 'AUT', value: 'Austria', alias: '', lemma: 'Austria' },
  {
    code: 'AUT',
    value: 'Austria (Salzburg)',
    alias: 'Salzburg',
    lemma: 'Austria',
  },
  { code: 'AUT', value: 'Austria (Vienna)', alias: 'Vienna', lemma: 'Austria' },
  { code: 'AZE', value: 'Azerbaijan', alias: '', lemma: 'Azerbaijan' },
  { code: 'BHS', value: 'Bahamas', alias: '', lemma: 'Bahamas' },
  { code: 'BHS', value: 'Bahamas (Nassau)', alias: 'Nassau', lemma: 'Bahamas' },
  { code: 'BHR', value: 'Bahrain', alias: '', lemma: 'Bahrain' },
  { code: 'BGD', value: 'Bangladesh', alias: '', lemma: 'Bangladesh' },
  {
    code: 'BGD',
    value: 'Bangladesh (Dhaka)',
    alias: 'Dhaka',
    lemma: 'Bangladesh',
  },
  { code: 'BRB', value: 'Barbados', alias: '', lemma: 'Barbados' },
  { code: 'BLR', value: 'Belarus', alias: '', lemma: 'Belarus' },
  { code: 'BEL', value: 'Belgium', alias: '', lemma: 'Belgium' },
  {
    code: 'BEL',
    value: 'Belgium (Brussels)',
    alias: 'Brussels',
    lemma: 'Belgium',
  },
  { code: 'BLZ', value: 'Belize', alias: '', lemma: 'Belize' },
  { code: 'BEN', value: 'Benin', alias: '', lemma: 'Benin' },
  { code: 'BMU', value: 'Bermuda', alias: '', lemma: 'Bermuda' },
  { code: 'BTN', value: 'Bhutan', alias: '', lemma: 'Bhutan' },
  { code: 'BOL', value: 'Bolivia', alias: '', lemma: 'Bolivia' },
  { code: 'BOL', value: 'Bolivia (La Paz)', alias: 'La Paz', lemma: 'Bolivia' },
  { code: 'BES', value: 'Bonaire', alias: '', lemma: 'Bonaire' },
  {
    code: 'BIH',
    value: 'Bosnia and Herzegovina',
    alias: '',
    lemma: 'Bosnia and Herzegovina',
  },
  { code: 'BWA', value: 'Botswana', alias: '', lemma: 'Botswana' },
  { code: 'BVT', value: 'Bouvet Island', alias: '', lemma: 'Bouvet Island' },
  { code: 'BRA', value: 'Brazil', alias: '', lemma: 'Brazil' },
  { code: 'BRA', value: 'Brazil (Brasil)', alias: 'Brasil', lemma: 'Brazil' },
  {
    code: 'BRA',
    value: 'Brazil (Rio de Janeiro)',
    alias: 'Rio de Janeiro',
    lemma: 'Brazil',
  },
  {
    code: 'BRA',
    value: 'Brazil (Salvador)',
    alias: 'Salvador',
    lemma: 'Brazil',
  },
  {
    code: 'BRA',
    value: 'Brazil (Sao Paulo)',
    alias: 'Sao Paulo',
    lemma: 'Brazil',
  },
  {
    code: 'IOT',
    value: 'British Indian Ocean Territory',
    alias: '',
    lemma: 'British Indian Ocean Territory',
  },
  {
    code: 'VGB',
    value: 'British Virgin Islands',
    alias: '',
    lemma: 'British Virgin Islands',
  },
  {
    code: 'VGB',
    value: 'British Virgin Islands (Anegada)',
    alias: 'Anegada',
    lemma: 'British Virgin Islands',
  },
  {
    code: 'VGB',
    value: 'British Virgin Islands (Jost Van Dyke)',
    alias: 'Jost Van Dyke',
    lemma: 'British Virgin Islands',
  },
  {
    code: 'VGB',
    value: 'British Virgin Islands (Tortola)',
    alias: 'Tortola',
    lemma: 'British Virgin Islands',
  },
  {
    code: 'VGB',
    value: 'British Virgin Islands (Virgin Gorda)',
    alias: 'Virgin Gorda',
    lemma: 'British Virgin Islands',
  },
  {
    code: 'BRN',
    value: 'Brunei Darussalam',
    alias: '',
    lemma: 'Brunei Darussalam',
  },
  { code: 'BGR', value: 'Bulgaria', alias: '', lemma: 'Bulgaria' },
  { code: 'BGR', value: 'Bulgaria (Sofia)', alias: 'Sofia', lemma: 'Bulgaria' },
  { code: 'BFA', value: 'Burkina Faso', alias: '', lemma: 'Burkina Faso' },
  { code: 'BDI', value: 'Burundi', alias: '', lemma: 'Burundi' },
  { code: 'KHM', value: 'Cambodia', alias: '', lemma: 'Cambodia' },
  {
    code: 'KHM',
    value: 'Cambodia (Phnom Penh)',
    alias: 'Phnom Penh',
    lemma: 'Cambodia',
  },
  {
    code: 'KHM',
    value: 'Cambodia (Siem Reap)',
    alias: 'Siem Reap',
    lemma: 'Cambodia',
  },
  { code: 'CMR', value: 'Cameroon', alias: '', lemma: 'Cameroon' },
  { code: 'CAN', value: 'Canada', alias: '', lemma: 'Canada' },
  { code: 'CAN', value: 'Canada (Alberta)', alias: 'Alberta', lemma: 'Canada' },
  { code: 'CAN', value: 'Canada (Banff)', alias: 'Banff', lemma: 'Canada' },
  {
    code: 'CAN',
    value: 'Canada (British Columbia)',
    alias: 'British Columbia',
    lemma: 'Canada',
  },
  { code: 'CAN', value: 'Canada (Calgary)', alias: 'Calgary', lemma: 'Canada' },
  {
    code: 'CAN',
    value: 'Canada (Manitoba)',
    alias: 'Manitoba',
    lemma: 'Canada',
  },
  {
    code: 'CAN',
    value: 'Canada (Montreal)',
    alias: 'Montreal',
    lemma: 'Canada',
  },
  {
    code: 'CAN',
    value: 'Canada (New Brunswick)',
    alias: 'New Brunswick',
    lemma: 'Canada',
  },
  {
    code: 'CAN',
    value: 'Canada (Newfoundland and Labrador)',
    alias: 'Newfoundland and Labrador',
    lemma: 'Canada',
  },
  {
    code: 'CAN',
    value: 'Canada (Niagra Falls)',
    alias: 'Niagra Falls',
    lemma: 'Canada',
  },
  {
    code: 'CAN',
    value: 'Canada (Nova Scotia)',
    alias: 'Nova Scotia',
    lemma: 'Canada',
  },
  { code: 'CAN', value: 'Canada (Ontario)', alias: 'Ontario', lemma: 'Canada' },
  { code: 'CAN', value: 'Canada (Ottawa)', alias: 'Ottawa', lemma: 'Canada' },
  {
    code: 'CAN',
    value: 'Canada (Prince Edward Island)',
    alias: 'Prince Edward Island',
    lemma: 'Canada',
  },
  {
    code: 'CAN',
    value: 'Canada (Quebec City)',
    alias: 'Quebec City',
    lemma: 'Canada',
  },
  { code: 'CAN', value: 'Canada (Quebec)', alias: 'Quebec', lemma: 'Canada' },
  {
    code: 'CAN',
    value: 'Canada (Saskatchewan)',
    alias: 'Saskatchewan',
    lemma: 'Canada',
  },
  { code: 'CAN', value: 'Canada (Toronto)', alias: 'Toronto', lemma: 'Canada' },
  {
    code: 'CAN',
    value: 'Canada (Vancouver)',
    alias: 'Vancouver',
    lemma: 'Canada',
  },
  {
    code: 'CAN',
    value: 'Canada (Victoria)',
    alias: 'Victoria',
    lemma: 'Canada',
  },
  {
    code: 'CAN',
    value: 'Canada (Whistler)',
    alias: 'Whistler',
    lemma: 'Canada',
  },
  { code: 'CPV', value: 'Cape Verde', alias: '', lemma: 'Cape Verde' },
  { code: 'Caribbean', value: 'Caribbean', alias: '', lemma: 'Caribbean' },
  { code: 'CYM', value: 'Cayman Islands', alias: '', lemma: 'Cayman Islands' },
  {
    code: 'CAF',
    value: 'Central African Republic',
    alias: '',
    lemma: 'Central African Republic',
  },
  { code: 'TCD', value: 'Chad', alias: '', lemma: 'Chad' },
  { code: 'CHL', value: 'Chile', alias: '', lemma: 'Chile' },
  {
    code: 'CHL',
    value: 'Chile (Easter Island)',
    alias: 'Easter Island',
    lemma: 'Chile',
  },
  {
    code: 'CHL',
    value: 'Chile (Patagonia)',
    alias: 'Patagonia',
    lemma: 'Chile',
  },
  { code: 'CHL', value: 'Chile (Santiago)', alias: 'Santiago', lemma: 'Chile' },
  { code: 'CHN', value: 'China', alias: '', lemma: 'China' },
  { code: 'CHN', value: 'China (Beijing)', alias: 'Beijing', lemma: 'China' },
  {
    code: 'CHN',
    value: 'China (Chongqing)',
    alias: 'Chongqing',
    lemma: 'China',
  },
  {
    code: 'CHN',
    value: 'China (Guangzhou)',
    alias: 'Guangzhou',
    lemma: 'China',
  },
  { code: 'CHN', value: 'China (Shanghai)', alias: 'Shanghai', lemma: 'China' },
  { code: 'CHN', value: 'China (Shenzhen)', alias: 'Shenzhen', lemma: 'China' },
  { code: 'CHN', value: 'China (Tibet)', alias: 'Tibet', lemma: 'China' },
  { code: 'CHN', value: 'China (Wenzhou)', alias: 'Wenzhou', lemma: 'China' },
  { code: 'CHN', value: "China (Xi'an)", alias: "Xi'an", lemma: 'China' },
  {
    code: 'CXR',
    value: 'Christmas Island',
    alias: '',
    lemma: 'Christmas Island',
  },
  {
    code: 'CCK',
    value: 'Cocos (Keeling) Islands',
    alias: '',
    lemma: 'Cocos (Keeling) Islands',
  },
  { code: 'COL', value: 'Colombia', alias: '', lemma: 'Colombia' },
  {
    code: 'COL',
    value: 'Colombia (Bogota)',
    alias: 'Bogota',
    lemma: 'Colombia',
  },
  { code: 'COM', value: 'Comoros', alias: '', lemma: 'Comoros' },
  { code: 'COG', value: 'Congo', alias: '', lemma: 'Congo' },
  { code: 'COG', value: 'Congo (Kinshasa)', alias: 'Kinshasa', lemma: 'Congo' },
  {
    code: 'COD',
    value: 'Congo, Democratic Republic of the',
    alias: '',
    lemma: 'Congo, Democratic Republic of the',
  },
  { code: 'COK', value: 'Cook Islands', alias: '', lemma: 'Cook Islands' },
  {
    code: 'COK',
    value: 'Cook Islands (Rarotonga)',
    alias: 'Rarotonga',
    lemma: 'Cook Islands',
  },
  { code: 'CRI', value: 'Costa Rica', alias: '', lemma: 'Costa Rica' },
  {
    code: 'CRI',
    value: 'Costa Rica (Monteverde)',
    alias: 'Monteverde',
    lemma: 'Costa Rica',
  },
  {
    code: 'CRI',
    value: 'Costa Rica (San Jose)',
    alias: 'San Jose',
    lemma: 'Costa Rica',
  },
  { code: 'CIV', value: "Cote d'Ivoire", alias: '', lemma: "Cote d'Ivoire" },
  { code: 'HRV', value: 'Croatia', alias: '', lemma: 'Croatia' },
  { code: 'CUB', value: 'Cuba', alias: '', lemma: 'Cuba' },
  { code: 'CUB', value: 'Cuba (Havana)', alias: 'Havana', lemma: 'Cuba' },
  { code: 'CUW', value: 'Curacao', alias: '', lemma: 'Curacao' },
  { code: 'CYP', value: 'Cyprus', alias: '', lemma: 'Cyprus' },
  { code: 'CZE', value: 'Czech Republic', alias: '', lemma: 'Czech Republic' },
  {
    code: 'CZE',
    value: 'Czech Republic (Prague)',
    alias: 'Prague',
    lemma: 'Czech Republic',
  },
  { code: 'DNK', value: 'Denmark', alias: '', lemma: 'Denmark' },
  {
    code: 'DNK',
    value: 'Denmark (Copenhagen)',
    alias: 'Copenhagen',
    lemma: 'Denmark',
  },
  {
    code: 'DNK',
    value: 'Denmark (Scandinavia)',
    alias: 'Scandinavia',
    lemma: 'Denmark',
  },
  { code: 'DJI', value: 'Djibouti', alias: '', lemma: 'Djibouti' },
  { code: 'DMA', value: 'Dominica', alias: '', lemma: 'Dominica' },
  {
    code: 'DOM',
    value: 'Dominican Republic',
    alias: '',
    lemma: 'Dominican Republic',
  },
  {
    code: 'DOM',
    value: 'Dominican Republic (Puerto Plata)',
    alias: 'Puerto Plata',
    lemma: 'Dominican Republic',
  },
  {
    code: 'DOM',
    value: 'Dominican Republic (Punta Cana)',
    alias: 'Punta Cana',
    lemma: 'Dominican Republic',
  },
  {
    code: 'DOM',
    value: 'Dominican Republic (Santo Domingo)',
    alias: 'Santo Domingo',
    lemma: 'Dominican Republic',
  },
  { code: 'ECU', value: 'Ecuador', alias: '', lemma: 'Ecuador' },
  {
    code: 'ECU',
    value: 'Ecuador (Galapagos Islands)',
    alias: 'Galapagos Islands',
    lemma: 'Ecuador',
  },
  { code: 'EGY', value: 'Egypt', alias: '', lemma: 'Egypt' },
  { code: 'EGY', value: 'Egypt (Cairo)', alias: 'Cairo', lemma: 'Egypt' },
  { code: 'SLV', value: 'El Salvador', alias: '', lemma: 'El Salvador' },
  {
    code: 'GNQ',
    value: 'Equatorial Guinea',
    alias: '',
    lemma: 'Equatorial Guinea',
  },
  { code: 'ERI', value: 'Eritrea', alias: '', lemma: 'Eritrea' },
  { code: 'EST', value: 'Estonia', alias: '', lemma: 'Estonia' },
  { code: 'ETH', value: 'Ethiopia', alias: '', lemma: 'Ethiopia' },
  {
    code: 'FLK',
    value: 'Falkland Islands (Malvinas)',
    alias: '',
    lemma: 'Falkland Islands (Malvinas)',
  },
  { code: 'FRO', value: 'Faroe Islands', alias: '', lemma: 'Faroe Islands' },
  { code: 'FJI', value: 'Fiji', alias: '', lemma: 'Fiji' },
  { code: 'FJI', value: 'Fiji (Nadi)', alias: 'Nadi', lemma: 'Fiji' },
  { code: 'FJI', value: 'Fiji (Suva)', alias: 'Suva', lemma: 'Fiji' },
  { code: 'FIN', value: 'Finland', alias: '', lemma: 'Finland' },
  {
    code: 'FIN',
    value: 'Finland (Helsinki)',
    alias: 'Helsinki',
    lemma: 'Finland',
  },
  {
    code: 'FIN',
    value: 'Finland (Lapland)',
    alias: 'Lapland',
    lemma: 'Finland',
  },
  {
    code: 'FIN',
    value: 'Finland (Scandinavia)',
    alias: 'Scandinavia',
    lemma: 'Finland',
  },
  { code: 'FRA', value: 'France', alias: '', lemma: 'France' },
  {
    code: 'FRA',
    value: 'France (Bordeaux)',
    alias: 'Bordeaux',
    lemma: 'France',
  },
  { code: 'FRA', value: 'France (Cannes)', alias: 'Cannes', lemma: 'France' },
  {
    code: 'FRA',
    value: 'France (Champagne)',
    alias: 'Champagne',
    lemma: 'France',
  },
  { code: 'FRA', value: 'France (Corsica)', alias: 'Corsica', lemma: 'France' },
  {
    code: 'FRA',
    value: 'France (Isle of Pines)',
    alias: 'Isle of Pines',
    lemma: 'France',
  },
  { code: 'FRA', value: 'France (Lifou)', alias: 'Lifou', lemma: 'France' },
  {
    code: 'FRA',
    value: 'France (Loyalty Islands)',
    alias: 'Loyalty Islands',
    lemma: 'France',
  },
  { code: 'FRA', value: 'France (Lyon)', alias: 'Lyon', lemma: 'France' },
  {
    code: 'FRA',
    value: 'France (Marseille)',
    alias: 'Marseille',
    lemma: 'France',
  },
  { code: 'FRA', value: 'France (Nice)', alias: 'Nice', lemma: 'France' },
  { code: 'FRA', value: 'France (Paris)', alias: 'Paris', lemma: 'France' },
  {
    code: 'FRA',
    value: 'France (Strasbourg)',
    alias: 'Strasbourg',
    lemma: 'France',
  },
  { code: 'GUF', value: 'French Guiana', alias: '', lemma: 'French Guiana' },
  {
    code: 'PYF',
    value: 'French Polynesia',
    alias: '',
    lemma: 'French Polynesia',
  },
  {
    code: 'PYF',
    value: 'French Polynesia (Bora Bora)',
    alias: 'Bora Bora',
    lemma: 'French Polynesia',
  },
  {
    code: 'PYF',
    value: 'French Polynesia (Fakarava)',
    alias: 'Fakarava',
    lemma: 'French Polynesia',
  },
  {
    code: 'PYF',
    value: 'French Polynesia (Fatu Hiva)',
    alias: 'Fatu Hiva',
    lemma: 'French Polynesia',
  },
  {
    code: 'PYF',
    value: 'French Polynesia (Hiva Oa)',
    alias: 'Hiva Oa',
    lemma: 'French Polynesia',
  },
  {
    code: 'PYF',
    value: 'French Polynesia (Huahine)',
    alias: 'Huahine',
    lemma: 'French Polynesia',
  },
  {
    code: 'PYF',
    value: 'French Polynesia (Mangareva)',
    alias: 'Mangareva',
    lemma: 'French Polynesia',
  },
  {
    code: 'PYF',
    value: 'French Polynesia (Manihi)',
    alias: 'Manihi',
    lemma: 'French Polynesia',
  },
  {
    code: 'PYF',
    value: 'French Polynesia (Maupiti)',
    alias: 'Maupiti',
    lemma: 'French Polynesia',
  },
  {
    code: 'PYF',
    value: 'French Polynesia (Moore)',
    alias: 'Moore',
    lemma: 'French Polynesia',
  },
  {
    code: 'PYF',
    value: 'French Polynesia (Nuka Hiva)',
    alias: 'Nuka Hiva',
    lemma: 'French Polynesia',
  },
  {
    code: 'PYF',
    value: 'French Polynesia (Raiatea)',
    alias: 'Raiatea',
    lemma: 'French Polynesia',
  },
  {
    code: 'PYF',
    value: 'French Polynesia (Rangiroa)',
    alias: 'Rangiroa',
    lemma: 'French Polynesia',
  },
  {
    code: 'PYF',
    value: 'French Polynesia (Rurutu)',
    alias: 'Rurutu',
    lemma: 'French Polynesia',
  },
  {
    code: 'PYF',
    value: 'French Polynesia (Taha\u2019a)',
    alias: 'Taha\u2019a',
    lemma: 'French Polynesia',
  },
  {
    code: 'PYF',
    value: 'French Polynesia (Tetiaroa)',
    alias: 'Tetiaroa',
    lemma: 'French Polynesia',
  },
  {
    code: 'PYF',
    value: 'French Polynesia (Tikehau)',
    alias: 'Tikehau',
    lemma: 'French Polynesia',
  },
  {
    code: 'ATF',
    value: 'French Southern Territories',
    alias: '',
    lemma: 'French Southern Territories',
  },
  { code: 'GAB', value: 'Gabon', alias: '', lemma: 'Gabon' },
  { code: 'GMB', value: 'Gambia', alias: '', lemma: 'Gambia' },
  { code: 'GEO', value: 'Georgia', alias: '', lemma: 'Georgia' },
  { code: 'DEU', value: 'Germany', alias: '', lemma: 'Germany' },
  { code: 'DEU', value: 'Germany (Berlin)', alias: 'Berlin', lemma: 'Germany' },
  {
    code: 'DEU',
    value: 'Germany (Cologne)',
    alias: 'Cologne',
    lemma: 'Germany',
  },
  {
    code: 'DEU',
    value: 'Germany (Dresden)',
    alias: 'Dresden',
    lemma: 'Germany',
  },
  {
    code: 'DEU',
    value: 'Germany (Frankfurt)',
    alias: 'Frankfurt',
    lemma: 'Germany',
  },
  {
    code: 'DEU',
    value: 'Germany (Hamburg)',
    alias: 'Hamburg',
    lemma: 'Germany',
  },
  { code: 'DEU', value: 'Germany (Munich)', alias: 'Munich', lemma: 'Germany' },
  {
    code: 'DEU',
    value: 'Germany (Nuremburg)',
    alias: 'Nuremburg',
    lemma: 'Germany',
  },
  { code: 'GHA', value: 'Ghana', alias: '', lemma: 'Ghana' },
  { code: 'GIB', value: 'Gibraltar', alias: '', lemma: 'Gibraltar' },
  { code: 'GRC', value: 'Greece', alias: '', lemma: 'Greece' },
  { code: 'GRC', value: 'Greece (Athens)', alias: 'Athens', lemma: 'Greece' },
  {
    code: 'GRC',
    value: 'Greece (Corfu Island)',
    alias: 'Corfu Island',
    lemma: 'Greece',
  },
  { code: 'GRC', value: 'Greece (Crete)', alias: 'Crete', lemma: 'Greece' },
  { code: 'GRC', value: 'Greece (Mykonos)', alias: 'Mykonos', lemma: 'Greece' },
  { code: 'GRC', value: 'Greece (Naxos)', alias: 'Naxos', lemma: 'Greece' },
  { code: 'GRC', value: 'Greece (Rhodes)', alias: 'Rhodes', lemma: 'Greece' },
  {
    code: 'GRC',
    value: 'Greece (Santorini)',
    alias: 'Santorini',
    lemma: 'Greece',
  },
  { code: 'GRL', value: 'Greenland', alias: '', lemma: 'Greenland' },
  { code: 'GRD', value: 'Grenada', alias: '', lemma: 'Grenada' },
  { code: 'GLP', value: 'Guadeloupe', alias: '', lemma: 'Guadeloupe' },
  { code: 'GUM', value: 'Guam', alias: '', lemma: 'Guam' },
  { code: 'GTM', value: 'Guatemala', alias: '', lemma: 'Guatemala' },
  {
    code: 'GTM',
    value: 'Guatemala (Guatemala City)',
    alias: 'Guatemala City',
    lemma: 'Guatemala',
  },
  { code: 'GGY', value: 'Guernsey', alias: '', lemma: 'Guernsey' },
  { code: 'GIN', value: 'Guinea', alias: '', lemma: 'Guinea' },
  { code: 'GNB', value: 'Guinea-Bissau', alias: '', lemma: 'Guinea-Bissau' },
  { code: 'GUY', value: 'Guyana', alias: '', lemma: 'Guyana' },
  { code: 'HTI', value: 'Haiti', alias: '', lemma: 'Haiti' },
  {
    code: 'HMD',
    value: 'Heard Island and McDonald Islands',
    alias: '',
    lemma: 'Heard Island and McDonald Islands',
  },
  {
    code: 'VAT',
    value: 'Holy See (Vatican City State)',
    alias: '',
    lemma: 'Holy See (Vatican City State)',
  },
  { code: 'HND', value: 'Honduras', alias: '', lemma: 'Honduras' },
  { code: 'HKG', value: 'Hong Kong', alias: '', lemma: 'Hong Kong' },
  {
    code: 'HKG',
    value: 'Hong Kong (Hongkong)',
    alias: 'Hongkong',
    lemma: 'Hong Kong',
  },
  { code: 'HUN', value: 'Hungary', alias: '', lemma: 'Hungary' },
  {
    code: 'HUN',
    value: 'Hungary (Budapest)',
    alias: 'Budapest',
    lemma: 'Hungary',
  },
  { code: 'ISL', value: 'Iceland', alias: '', lemma: 'Iceland' },
  {
    code: 'ISL',
    value: 'Iceland (Reykjavik)',
    alias: 'Reykjavik',
    lemma: 'Iceland',
  },
  {
    code: 'ISL',
    value: 'Iceland (Scandinavia)',
    alias: 'Scandinavia',
    lemma: 'Iceland',
  },
  { code: 'IND', value: 'India', alias: '', lemma: 'India' },
  { code: 'IND', value: 'India (Agra)', alias: 'Agra', lemma: 'India' },
  {
    code: 'IND',
    value: 'India (Ahmedabad)',
    alias: 'Ahmedabad',
    lemma: 'India',
  },
  {
    code: 'IND',
    value: 'India (Bangalore)',
    alias: 'Bangalore',
    lemma: 'India',
  },
  {
    code: 'IND',
    value: 'India (Bengaluru)',
    alias: 'Bengaluru',
    lemma: 'India',
  },
  { code: 'IND', value: 'India (Chennai)', alias: 'Chennai', lemma: 'India' },
  { code: 'IND', value: 'India (Delhi)', alias: 'Delhi', lemma: 'India' },
  {
    code: 'IND',
    value: 'India (Hyderabad)',
    alias: 'Hyderabad',
    lemma: 'India',
  },
  { code: 'IND', value: 'India (Mumbai)', alias: 'Mumbai', lemma: 'India' },
  {
    code: 'IND',
    value: 'India (New Delhi)',
    alias: 'New Delhi',
    lemma: 'India',
  },
  { code: 'IND', value: 'India (Pune)', alias: 'Pune', lemma: 'India' },
  { code: 'IND', value: 'India (Vadodara)', alias: 'Vadodara', lemma: 'India' },
  { code: 'IDN', value: 'Indonesia', alias: '', lemma: 'Indonesia' },
  { code: 'IDN', value: 'Indonesia (Bali)', alias: 'Bali', lemma: 'Indonesia' },
  {
    code: 'IDN',
    value: 'Indonesia (Jakarta)',
    alias: 'Jakarta',
    lemma: 'Indonesia',
  },
  {
    code: 'IDN',
    value: 'Indonesia (Lombok)',
    alias: 'Lombok',
    lemma: 'Indonesia',
  },
  { code: 'IRQ', value: 'Iraq', alias: '', lemma: 'Iraq' },
  { code: 'IRQ', value: 'Iraq (Baghdad)', alias: 'Baghdad', lemma: 'Iraq' },
  { code: 'IRL', value: 'Ireland', alias: '', lemma: 'Ireland' },
  {
    code: 'IRL',
    value: 'Ireland (Belfast)',
    alias: 'Belfast',
    lemma: 'Ireland',
  },
  { code: 'IRL', value: 'Ireland (Cork)', alias: 'Cork', lemma: 'Ireland' },
  { code: 'IRL', value: 'Ireland (Dublin)', alias: 'Dublin', lemma: 'Ireland' },
  { code: 'IRL', value: 'Ireland (Galway)', alias: 'Galway', lemma: 'Ireland' },
  {
    code: 'IRL',
    value: 'Ireland (Killarney)',
    alias: 'Killarney',
    lemma: 'Ireland',
  },
  {
    code: 'IRL',
    value: 'Ireland (Limerick)',
    alias: 'Limerick',
    lemma: 'Ireland',
  },
  {
    code: 'IRL',
    value: 'Ireland (Republic of Ireland)',
    alias: 'Republic of Ireland',
    lemma: 'Ireland',
  },
  { code: 'IMN', value: 'Isle of Man', alias: '', lemma: 'Isle of Man' },
  { code: 'ISR', value: 'Israel', alias: '', lemma: 'Israel' },
  {
    code: 'ISR',
    value: 'Israel (Beersheba)',
    alias: 'Beersheba',
    lemma: 'Israel',
  },
  { code: 'ISR', value: 'Israel (Eilat)', alias: 'Eilat', lemma: 'Israel' },
  { code: 'ISR', value: 'Israel (Haifa)', alias: 'Haifa', lemma: 'Israel' },
  {
    code: 'ISR',
    value: 'Israel (Jerusalem)',
    alias: 'Jerusalem',
    lemma: 'Israel',
  },
  {
    code: 'ISR',
    value: 'Israel (Nazareth)',
    alias: 'Nazareth',
    lemma: 'Israel',
  },
  {
    code: 'ISR',
    value: 'Israel (Tel Aviv)',
    alias: 'Tel Aviv',
    lemma: 'Israel',
  },
  { code: 'ITA', value: 'Italy', alias: '', lemma: 'Italy' },
  { code: 'ITA', value: 'Italy (Bologna)', alias: 'Bologna', lemma: 'Italy' },
  { code: 'ITA', value: 'Italy (Florence)', alias: 'Florence', lemma: 'Italy' },
  { code: 'ITA', value: 'Italy (Genoa)', alias: 'Genoa', lemma: 'Italy' },
  { code: 'ITA', value: 'Italy (Milan)', alias: 'Milan', lemma: 'Italy' },
  { code: 'ITA', value: 'Italy (Naples)', alias: 'Naples', lemma: 'Italy' },
  { code: 'ITA', value: 'Italy (Perugia)', alias: 'Perugia', lemma: 'Italy' },
  { code: 'ITA', value: 'Italy (Rome)', alias: 'Rome', lemma: 'Italy' },
  { code: 'ITA', value: 'Italy (Sicily)', alias: 'Sicily', lemma: 'Italy' },
  { code: 'ITA', value: 'Italy (Turin)', alias: 'Turin', lemma: 'Italy' },
  { code: 'ITA', value: 'Italy (Venice)', alias: 'Venice', lemma: 'Italy' },
  { code: 'ITA', value: 'Italy (Verona)', alias: 'Verona', lemma: 'Italy' },
  { code: 'JAM', value: 'Jamaica', alias: '', lemma: 'Jamaica' },
  {
    code: 'JAM',
    value: 'Jamaica (Kingston)',
    alias: 'Kingston',
    lemma: 'Jamaica',
  },
  {
    code: 'JAM',
    value: 'Jamaica (Montego Bay)',
    alias: 'Montego Bay',
    lemma: 'Jamaica',
  },
  { code: 'JAM', value: 'Jamaica (Negril)', alias: 'Negril', lemma: 'Jamaica' },
  {
    code: 'JAM',
    value: 'Jamaica (Ocho Rios)',
    alias: 'Ocho Rios',
    lemma: 'Jamaica',
  },
  { code: 'JPN', value: 'Japan', alias: '', lemma: 'Japan' },
  {
    code: 'JPN',
    value: 'Japan (Hiroshima)',
    alias: 'Hiroshima',
    lemma: 'Japan',
  },
  { code: 'JPN', value: 'Japan (Kyoto)', alias: 'Kyoto', lemma: 'Japan' },
  { code: 'JPN', value: 'Japan (Nara)', alias: 'Nara', lemma: 'Japan' },
  { code: 'JPN', value: 'Japan (Osaka)', alias: 'Osaka', lemma: 'Japan' },
  { code: 'JPN', value: 'Japan (Sapporo)', alias: 'Sapporo', lemma: 'Japan' },
  { code: 'JPN', value: 'Japan (Tokyo)', alias: 'Tokyo', lemma: 'Japan' },
  { code: 'JPN', value: 'Japan (Yokohama)', alias: 'Yokohama', lemma: 'Japan' },
  { code: 'JEY', value: 'Jersey', alias: '', lemma: 'Jersey' },
  { code: 'JOR', value: 'Jordan', alias: '', lemma: 'Jordan' },
  { code: 'JOR', value: 'Jordan (Amman)', alias: 'Amman', lemma: 'Jordan' },
  { code: 'KAZ', value: 'Kazakhstan', alias: '', lemma: 'Kazakhstan' },
  { code: 'KEN', value: 'Kenya', alias: '', lemma: 'Kenya' },
  { code: 'KEN', value: 'Kenya (Nairobi)', alias: 'Nairobi', lemma: 'Kenya' },
  { code: 'KIR', value: 'Kiribati', alias: '', lemma: 'Kiribati' },
  {
    code: 'KOR',
    value: 'Korea, (South) Republic of',
    alias: '',
    lemma: 'Korea, (South) Republic of',
  },
  {
    code: 'KOR',
    value: 'Korea, (South) Republic of (Seoul)',
    alias: 'Seoul',
    lemma: 'Korea, (South) Republic of',
  },
  { code: 'KWT', value: 'Kuwait', alias: '', lemma: 'Kuwait' },
  {
    code: 'KWT',
    value: 'Kuwait (Kuwait City)',
    alias: 'Kuwait City',
    lemma: 'Kuwait',
  },
  { code: 'KGZ', value: 'Kyrgyzstan', alias: '', lemma: 'Kyrgyzstan' },
  {
    code: 'LAO',
    value: "Lao People's Democratic Republic (Laos)",
    alias: '',
    lemma: "Lao People's Democratic Republic (Laos)",
  },
  { code: 'LVA', value: 'Latvia', alias: '', lemma: 'Latvia' },
  { code: 'LBN', value: 'Lebanon', alias: '', lemma: 'Lebanon' },
  { code: 'LBN', value: 'Lebanon (Beirut)', alias: 'Beirut', lemma: 'Lebanon' },
  { code: 'LSO', value: 'Lesotho', alias: '', lemma: 'Lesotho' },
  { code: 'LBR', value: 'Liberia', alias: '', lemma: 'Liberia' },
  {
    code: 'LBY',
    value: 'Libyan Arab Jamahiriya (Libya)',
    alias: '',
    lemma: 'Libyan Arab Jamahiriya (Libya)',
  },
  { code: 'LIE', value: 'Liechtenstein', alias: '', lemma: 'Liechtenstein' },
  { code: 'LTU', value: 'Lithuania', alias: '', lemma: 'Lithuania' },
  { code: 'LUX', value: 'Luxembourg', alias: '', lemma: 'Luxembourg' },
  { code: 'MAC', value: 'Macao', alias: '', lemma: 'Macao' },
  { code: 'MAC', value: 'Macao (Macau)', alias: 'Macau', lemma: 'Macao' },
  {
    code: 'MKD',
    value: 'Macedonia, the former Yugoslav Republic of',
    alias: '',
    lemma: 'Macedonia, the former Yugoslav Republic of',
  },
  { code: 'MDG', value: 'Madagascar', alias: '', lemma: 'Madagascar' },
  { code: 'MWI', value: 'Malawi', alias: '', lemma: 'Malawi' },
  { code: 'MYS', value: 'Malaysia', alias: '', lemma: 'Malaysia' },
  { code: 'MYS', value: 'Malaysia (KL)', alias: 'KL', lemma: 'Malaysia' },
  {
    code: 'MYS',
    value: 'Malaysia (Kuala Lumpur)',
    alias: 'Kuala Lumpur',
    lemma: 'Malaysia',
  },
  { code: 'MDV', value: 'Maldives', alias: '', lemma: 'Maldives' },
  { code: 'MLI', value: 'Mali', alias: '', lemma: 'Mali' },
  { code: 'MLT', value: 'Malta', alias: '', lemma: 'Malta' },
  {
    code: 'MHL',
    value: 'Marshall Islands',
    alias: '',
    lemma: 'Marshall Islands',
  },
  { code: 'MTQ', value: 'Martinique', alias: '', lemma: 'Martinique' },
  { code: 'MRT', value: 'Mauritania', alias: '', lemma: 'Mauritania' },
  { code: 'MUS', value: 'Mauritius', alias: '', lemma: 'Mauritius' },
  { code: 'MYT', value: 'Mayotte', alias: '', lemma: 'Mayotte' },
  { code: 'MEX', value: 'Mexico', alias: '', lemma: 'Mexico' },
  {
    code: 'MEX',
    value: 'Mexico (Cabo San Lucas)',
    alias: 'Cabo San Lucas',
    lemma: 'Mexico',
  },
  { code: 'MEX', value: 'Mexico (Cancun)', alias: 'Cancun', lemma: 'Mexico' },
  { code: 'MEX', value: 'Mexico (Cozumel)', alias: 'Cozumel', lemma: 'Mexico' },
  {
    code: 'MEX',
    value: 'Mexico (Guadalajara)',
    alias: 'Guadalajara',
    lemma: 'Mexico',
  },
  {
    code: 'MEX',
    value: 'Mexico (Mexico City)',
    alias: 'Mexico City',
    lemma: 'Mexico',
  },
  {
    code: 'MEX',
    value: 'Mexico (Playa del Carmen)',
    alias: 'Playa del Carmen',
    lemma: 'Mexico',
  },
  {
    code: 'MEX',
    value: 'Mexico (Puerto Vallarta)',
    alias: 'Puerto Vallarta',
    lemma: 'Mexico',
  },
  {
    code: 'MEX',
    value: 'Mexico (San Miguel de Allende)',
    alias: 'San Miguel de Allende',
    lemma: 'Mexico',
  },
  { code: 'MEX', value: 'Mexico (Tulum)', alias: 'Tulum', lemma: 'Mexico' },
  {
    code: 'FSM',
    value: 'Micronesia, Federated States of',
    alias: '',
    lemma: 'Micronesia, Federated States of',
  },
  { code: 'MDA', value: 'Moldova', alias: '', lemma: 'Moldova' },
  { code: 'MCO', value: 'Monaco', alias: '', lemma: 'Monaco' },
  { code: 'MNG', value: 'Mongolia', alias: '', lemma: 'Mongolia' },
  { code: 'MNE', value: 'Montenegro', alias: '', lemma: 'Montenegro' },
  { code: 'MSR', value: 'Montserrat', alias: '', lemma: 'Montserrat' },
  {
    code: 'MSR',
    value: 'Montserrat (Monserrat)',
    alias: 'Monserrat',
    lemma: 'Montserrat',
  },
  { code: 'MAR', value: 'Morocco', alias: '', lemma: 'Morocco' },
  {
    code: 'MAR',
    value: 'Morocco (Casablanca)',
    alias: 'Casablanca',
    lemma: 'Morocco',
  },
  {
    code: 'MAR',
    value: 'Morocco (Marrakech)',
    alias: 'Marrakech',
    lemma: 'Morocco',
  },
  { code: 'MOZ', value: 'Mozambique', alias: '', lemma: 'Mozambique' },
  { code: 'MMR', value: 'Myanmar', alias: '', lemma: 'Myanmar' },
  { code: 'MMR', value: 'Myanmar (Burma)', alias: 'Burma', lemma: 'Myanmar' },
  { code: 'NAM', value: 'Namibia', alias: '', lemma: 'Namibia' },
  { code: 'NRU', value: 'Nauru', alias: '', lemma: 'Nauru' },
  { code: 'NPL', value: 'Nepal', alias: '', lemma: 'Nepal' },
  {
    code: 'NPL',
    value: 'Nepal (Kathmandu)',
    alias: 'Kathmandu',
    lemma: 'Nepal',
  },
  { code: 'NLD', value: 'Netherlands', alias: '', lemma: 'Netherlands' },
  {
    code: 'NLD',
    value: 'Netherlands (Amsterdam)',
    alias: 'Amsterdam',
    lemma: 'Netherlands',
  },
  {
    code: 'NLD',
    value: 'Netherlands (Holland)',
    alias: 'Holland',
    lemma: 'Netherlands',
  },
  {
    code: 'NLD',
    value: 'Netherlands (Maastricht)',
    alias: 'Maastricht',
    lemma: 'Netherlands',
  },
  {
    code: 'NLD',
    value: 'Netherlands (Rotterdam)',
    alias: 'Rotterdam',
    lemma: 'Netherlands',
  },
  {
    code: 'NLD',
    value: 'Netherlands (Saba)',
    alias: 'Saba',
    lemma: 'Netherlands',
  },
  {
    code: 'NLD',
    value: 'Netherlands (Sint Eustatius)',
    alias: 'Sint Eustatius',
    lemma: 'Netherlands',
  },
  {
    code: 'NLD',
    value: 'Netherlands (St Eustatius)',
    alias: 'St Eustatius',
    lemma: 'Netherlands',
  },
  {
    code: 'NLD',
    value: 'Netherlands (St. Eustatius)',
    alias: 'St. Eustatius',
    lemma: 'Netherlands',
  },
  {
    code: 'NLD',
    value: 'Netherlands (The Hague)',
    alias: 'The Hague',
    lemma: 'Netherlands',
  },
  { code: 'NCL', value: 'New Caledonia', alias: '', lemma: 'New Caledonia' },
  {
    code: 'NCL',
    value: 'New Caledonia (Noumea)',
    alias: 'Noumea',
    lemma: 'New Caledonia',
  },
  { code: 'NZL', value: 'New Zealand', alias: '', lemma: 'New Zealand' },
  {
    code: 'NZL',
    value: 'New Zealand (Auckland)',
    alias: 'Auckland',
    lemma: 'New Zealand',
  },
  {
    code: 'NZL',
    value: 'New Zealand (Christchurch)',
    alias: 'Christchurch',
    lemma: 'New Zealand',
  },
  {
    code: 'NZL',
    value: 'New Zealand (Newzealand)',
    alias: 'Newzealand',
    lemma: 'New Zealand',
  },
  {
    code: 'NZL',
    value: 'New Zealand (Wellington)',
    alias: 'Wellington',
    lemma: 'New Zealand',
  },
  { code: 'NIC', value: 'Nicaragua', alias: '', lemma: 'Nicaragua' },
  { code: 'NER', value: 'Niger', alias: '', lemma: 'Niger' },
  { code: 'NGA', value: 'Nigeria', alias: '', lemma: 'Nigeria' },
  { code: 'NIU', value: 'Niue', alias: '', lemma: 'Niue' },
  { code: 'NFK', value: 'Norfolk Island', alias: '', lemma: 'Norfolk Island' },
  {
    code: 'MNP',
    value: 'Northern Mariana Islands',
    alias: '',
    lemma: 'Northern Mariana Islands',
  },
  { code: 'NOR', value: 'Norway', alias: '', lemma: 'Norway' },
  { code: 'NOR', value: 'Norway (Oslo)', alias: 'Oslo', lemma: 'Norway' },
  {
    code: 'NOR',
    value: 'Norway (Scandinavia)',
    alias: 'Scandinavia',
    lemma: 'Norway',
  },
  { code: 'OMN', value: 'Oman', alias: '', lemma: 'Oman' },
  { code: 'Other', value: 'Other', alias: '', lemma: 'Other' },
  { code: 'PAK', value: 'Pakistan', alias: '', lemma: 'Pakistan' },
  {
    code: 'PAK',
    value: 'Pakistan (Islamabad)',
    alias: 'Islamabad',
    lemma: 'Pakistan',
  },
  {
    code: 'PAK',
    value: 'Pakistan (Karachi)',
    alias: 'Karachi',
    lemma: 'Pakistan',
  },
  {
    code: 'PAK',
    value: 'Pakistan (Lahore)',
    alias: 'Lahore',
    lemma: 'Pakistan',
  },
  { code: 'PLW', value: 'Palau', alias: '', lemma: 'Palau' },
  {
    code: 'PSE',
    value: 'Palestinian Territory, Occupied',
    alias: '',
    lemma: 'Palestinian Territory, Occupied',
  },
  {
    code: 'PSE',
    value: 'Palestinian Territory, Occupied (Gaza Strip)',
    alias: 'Gaza Strip',
    lemma: 'Palestinian Territory, Occupied',
  },
  {
    code: 'PSE',
    value: 'Palestinian Territory, Occupied (Palestine)',
    alias: 'Palestine',
    lemma: 'Palestinian Territory, Occupied',
  },
  {
    code: 'PSE',
    value: 'Palestinian Territory, Occupied (West Bank)',
    alias: 'West Bank',
    lemma: 'Palestinian Territory, Occupied',
  },
  { code: 'PAN', value: 'Panama', alias: '', lemma: 'Panama' },
  {
    code: 'PAN',
    value: 'Panama (Panama City)',
    alias: 'Panama City',
    lemma: 'Panama',
  },
  {
    code: 'PNG',
    value: 'Papua New Guinea',
    alias: '',
    lemma: 'Papua New Guinea',
  },
  {
    code: 'PNG',
    value: 'Papua New Guinea (Port Moresby)',
    alias: 'Port Moresby',
    lemma: 'Papua New Guinea',
  },
  { code: 'PRY', value: 'Paraguay', alias: '', lemma: 'Paraguay' },
  { code: 'PER', value: 'Peru', alias: '', lemma: 'Peru' },
  { code: 'PER', value: 'Peru (Cusco)', alias: 'Cusco', lemma: 'Peru' },
  { code: 'PER', value: 'Peru (Lima)', alias: 'Lima', lemma: 'Peru' },
  {
    code: 'PER',
    value: 'Peru (Machu Picchu)',
    alias: 'Machu Picchu',
    lemma: 'Peru',
  },
  { code: 'PHL', value: 'Philippines', alias: '', lemma: 'Philippines' },
  {
    code: 'PHL',
    value: 'Philippines (Cebu)',
    alias: 'Cebu',
    lemma: 'Philippines',
  },
  {
    code: 'PHL',
    value: 'Philippines (Manila)',
    alias: 'Manila',
    lemma: 'Philippines',
  },
  { code: 'PCN', value: 'Pitcairn', alias: '', lemma: 'Pitcairn' },
  {
    code: 'PCN',
    value: 'Pitcairn (Pitcairn Island)',
    alias: 'Pitcairn Island',
    lemma: 'Pitcairn',
  },
  { code: 'POL', value: 'Poland', alias: '', lemma: 'Poland' },
  { code: 'POL', value: 'Poland (Warsaw)', alias: 'Warsaw', lemma: 'Poland' },
  { code: 'PRT', value: 'Portugal', alias: '', lemma: 'Portugal' },
  {
    code: 'PRT',
    value: 'Portugal (Azores)',
    alias: 'Azores',
    lemma: 'Portugal',
  },
  {
    code: 'PRT',
    value: 'Portugal (Dubrovnik)',
    alias: 'Dubrovnik',
    lemma: 'Portugal',
  },
  {
    code: 'PRT',
    value: 'Portugal (Lisbon)',
    alias: 'Lisbon',
    lemma: 'Portugal',
  },
  { code: 'PRI', value: 'Puerto Rico', alias: '', lemma: 'Puerto Rico' },
  { code: 'QAT', value: 'Qatar', alias: '', lemma: 'Qatar' },
  { code: 'QAT', value: 'Qatar (Doha)', alias: 'Doha', lemma: 'Qatar' },
  { code: 'REU', value: 'Reunion', alias: '', lemma: 'Reunion' },
  { code: 'ROU', value: 'Romania', alias: '', lemma: 'Romania' },
  {
    code: 'ROU',
    value: 'Romania (Bucharest)',
    alias: 'Bucharest',
    lemma: 'Romania',
  },
  { code: 'RUS', value: 'Russia', alias: '', lemma: 'Russia' },
  { code: 'RUS', value: 'Russia (Moscow)', alias: 'Moscow', lemma: 'Russia' },
  {
    code: 'RUS',
    value: 'Russia (Saint Petersberg)',
    alias: 'Saint Petersberg',
    lemma: 'Russia',
  },
  {
    code: 'RUS',
    value: 'Russia (St Petersberg)',
    alias: 'St Petersberg',
    lemma: 'Russia',
  },
  {
    code: 'RUS',
    value: 'Russia (St. Petersberg)',
    alias: 'St. Petersberg',
    lemma: 'Russia',
  },
  { code: 'RWA', value: 'Rwanda', alias: '', lemma: 'Rwanda' },
  {
    code: 'BLM',
    value: 'Saint Barthelemy',
    alias: '',
    lemma: 'Saint Barthelemy',
  },
  {
    code: 'BLM',
    value: 'Saint Barthelemy (Saint Barths)',
    alias: 'Saint Barths',
    lemma: 'Saint Barthelemy',
  },
  {
    code: 'BLM',
    value: 'Saint Barthelemy (Saint Barts)',
    alias: 'Saint Barts',
    lemma: 'Saint Barthelemy',
  },
  {
    code: 'BLM',
    value: 'Saint Barthelemy (St Barthelemy)',
    alias: 'St Barthelemy',
    lemma: 'Saint Barthelemy',
  },
  {
    code: 'BLM',
    value: 'Saint Barthelemy (St Barths)',
    alias: 'St Barths',
    lemma: 'Saint Barthelemy',
  },
  {
    code: 'BLM',
    value: 'Saint Barthelemy (St Barts)',
    alias: 'St Barts',
    lemma: 'Saint Barthelemy',
  },
  {
    code: 'BLM',
    value: 'Saint Barthelemy (St. Barthelemy)',
    alias: 'St. Barthelemy',
    lemma: 'Saint Barthelemy',
  },
  {
    code: 'BLM',
    value: 'Saint Barthelemy (St. Barths)',
    alias: 'St. Barths',
    lemma: 'Saint Barthelemy',
  },
  {
    code: 'BLM',
    value: 'Saint Barthelemy (St. Barts)',
    alias: 'St. Barts',
    lemma: 'Saint Barthelemy',
  },
  { code: 'SHN', value: 'Saint Helena', alias: '', lemma: 'Saint Helena' },
  {
    code: 'SHN',
    value: 'Saint Helena (Ascension)',
    alias: 'Ascension',
    lemma: 'Saint Helena',
  },
  {
    code: 'SHN',
    value: 'Saint Helena (St Helena)',
    alias: 'St Helena',
    lemma: 'Saint Helena',
  },
  {
    code: 'SHN',
    value: 'Saint Helena (St. Helena)',
    alias: 'St. Helena',
    lemma: 'Saint Helena',
  },
  {
    code: 'SHN',
    value: 'Saint Helena (Tristan da Cunha)',
    alias: 'Tristan da Cunha',
    lemma: 'Saint Helena',
  },
  {
    code: 'KNA',
    value: 'Saint Kitts and Nevis',
    alias: '',
    lemma: 'Saint Kitts and Nevis',
  },
  {
    code: 'KNA',
    value: 'Saint Kitts and Nevis (St Kitts and Nevis)',
    alias: 'St Kitts and Nevis',
    lemma: 'Saint Kitts and Nevis',
  },
  {
    code: 'KNA',
    value: 'Saint Kitts and Nevis (St. Kitts and Nevis)',
    alias: 'St. Kitts and Nevis',
    lemma: 'Saint Kitts and Nevis',
  },
  { code: 'LCA', value: 'Saint Lucia', alias: '', lemma: 'Saint Lucia' },
  {
    code: 'LCA',
    value: 'Saint Lucia (St Lucia)',
    alias: 'St Lucia',
    lemma: 'Saint Lucia',
  },
  {
    code: 'LCA',
    value: 'Saint Lucia (St. Lucia)',
    alias: 'St. Lucia',
    lemma: 'Saint Lucia',
  },
  { code: 'MAF', value: 'Saint Martin', alias: '', lemma: 'Saint Martin' },
  {
    code: 'MAF',
    value: 'Saint Martin (St Martin)',
    alias: 'St Martin',
    lemma: 'Saint Martin',
  },
  {
    code: 'MAF',
    value: 'Saint Martin (St. Martin)',
    alias: 'St. Martin',
    lemma: 'Saint Martin',
  },
  {
    code: 'SPM',
    value: 'Saint Pierre and Miquelon',
    alias: '',
    lemma: 'Saint Pierre and Miquelon',
  },
  {
    code: 'SPM',
    value: 'Saint Pierre and Miquelon (St Pierre and Miquelon)',
    alias: 'St Pierre and Miquelon',
    lemma: 'Saint Pierre and Miquelon',
  },
  {
    code: 'SPM',
    value: 'Saint Pierre and Miquelon (St. Pierre and Miquelon)',
    alias: 'St. Pierre and Miquelon',
    lemma: 'Saint Pierre and Miquelon',
  },
  {
    code: 'VCT',
    value: 'Saint Vincent and the Grenadines',
    alias: '',
    lemma: 'Saint Vincent and the Grenadines',
  },
  {
    code: 'VCT',
    value: 'Saint Vincent and the Grenadines (St Vincent and the Grenadines)',
    alias: 'St Vincent and the Grenadines',
    lemma: 'Saint Vincent and the Grenadines',
  },
  {
    code: 'VCT',
    value: 'Saint Vincent and the Grenadines (St. Vincent and the Grenadines)',
    alias: 'St. Vincent and the Grenadines',
    lemma: 'Saint Vincent and the Grenadines',
  },
  { code: 'WSM', value: 'Samoa', alias: '', lemma: 'Samoa' },
  {
    code: 'WSM',
    value: 'Samoa (Western Samoa)',
    alias: 'Western Samoa',
    lemma: 'Samoa',
  },
  { code: 'SMR', value: 'San Marino', alias: '', lemma: 'San Marino' },
  {
    code: 'STP',
    value: 'Sao Tome and Principe',
    alias: '',
    lemma: 'Sao Tome and Principe',
  },
  { code: 'SAU', value: 'Saudi Arabia', alias: '', lemma: 'Saudi Arabia' },
  {
    code: 'SAU',
    value: 'Saudi Arabia (Mecca)',
    alias: 'Mecca',
    lemma: 'Saudi Arabia',
  },
  {
    code: 'SAU',
    value: 'Saudi Arabia (Riyadh)',
    alias: 'Riyadh',
    lemma: 'Saudi Arabia',
  },
  { code: 'SEN', value: 'Senegal', alias: '', lemma: 'Senegal' },
  { code: 'SRB', value: 'Serbia', alias: '', lemma: 'Serbia' },
  {
    code: 'SRB',
    value: 'Serbia (Belgrade)',
    alias: 'Belgrade',
    lemma: 'Serbia',
  },
  { code: 'SYC', value: 'Seychelles', alias: '', lemma: 'Seychelles' },
  { code: 'SLE', value: 'Sierra Leone', alias: '', lemma: 'Sierra Leone' },
  { code: 'SGP', value: 'Singapore', alias: '', lemma: 'Singapore' },
  { code: 'SXM', value: 'Sint Maarten', alias: '', lemma: 'Sint Maarten' },
  {
    code: 'SXM',
    value: 'Sint Maarten (St Maarten)',
    alias: 'St Maarten',
    lemma: 'Sint Maarten',
  },
  {
    code: 'SXM',
    value: 'Sint Maarten (St. Maarten)',
    alias: 'St. Maarten',
    lemma: 'Sint Maarten',
  },
  { code: 'SVK', value: 'Slovakia', alias: '', lemma: 'Slovakia' },
  { code: 'SVN', value: 'Slovenia', alias: '', lemma: 'Slovenia' },
  {
    code: 'SLB',
    value: 'Solomon Islands',
    alias: '',
    lemma: 'Solomon Islands',
  },
  { code: 'SOM', value: 'Somalia', alias: '', lemma: 'Somalia' },
  { code: 'ZAF', value: 'South Africa', alias: '', lemma: 'South Africa' },
  {
    code: 'ZAF',
    value: 'South Africa (Cape Town)',
    alias: 'Cape Town',
    lemma: 'South Africa',
  },
  {
    code: 'ZAF',
    value: 'South Africa (Johannesburg)',
    alias: 'Johannesburg',
    lemma: 'South Africa',
  },
  {
    code: 'SGS',
    value: 'South Georgia and the South Sandwich Islands',
    alias: '',
    lemma: 'South Georgia and the South Sandwich Islands',
  },
  { code: 'SSD', value: 'South Sudan', alias: '', lemma: 'South Sudan' },
  { code: 'ESP', value: 'Spain', alias: '', lemma: 'Spain' },
  {
    code: 'ESP',
    value: 'Spain (Barcelona)',
    alias: 'Barcelona',
    lemma: 'Spain',
  },
  {
    code: 'ESP',
    value: 'Spain (Canary Islands)',
    alias: 'Canary Islands',
    lemma: 'Spain',
  },
  { code: 'ESP', value: 'Spain (Espana)', alias: 'Espana', lemma: 'Spain' },
  { code: 'ESP', value: 'Spain (Granada)', alias: 'Granada', lemma: 'Spain' },
  { code: 'ESP', value: 'Spain (Ibiza)', alias: 'Ibiza', lemma: 'Spain' },
  {
    code: 'ESP',
    value: 'Spain (Lanzarote)',
    alias: 'Lanzarote',
    lemma: 'Spain',
  },
  { code: 'ESP', value: 'Spain (Madrid)', alias: 'Madrid', lemma: 'Spain' },
  { code: 'ESP', value: 'Spain (Seville)', alias: 'Seville', lemma: 'Spain' },
  { code: 'ESP', value: 'Spain (Tenerife)', alias: 'Tenerife', lemma: 'Spain' },
  { code: 'ESP', value: 'Spain (Valencia)', alias: 'Valencia', lemma: 'Spain' },
  { code: 'LKA', value: 'Sri Lanka', alias: '', lemma: 'Sri Lanka' },
  {
    code: 'LKA',
    value: 'Sri Lanka (SriLanka)',
    alias: 'SriLanka',
    lemma: 'Sri Lanka',
  },
  { code: 'SDN', value: 'Sudan', alias: '', lemma: 'Sudan' },
  {
    code: 'SDN',
    value: 'Sudan (South Sudan)',
    alias: 'South Sudan',
    lemma: 'Sudan',
  },
  { code: 'SUR', value: 'Suriname', alias: '', lemma: 'Suriname' },
  {
    code: 'SJM',
    value: 'Svalbard and Jan Mayen',
    alias: '',
    lemma: 'Svalbard and Jan Mayen',
  },
  { code: 'SWE', value: 'Sweden', alias: '', lemma: 'Sweden' },
  {
    code: 'SWE',
    value: 'Sweden (Scandinavia)',
    alias: 'Scandinavia',
    lemma: 'Sweden',
  },
  {
    code: 'SWE',
    value: 'Sweden (Stockholm)',
    alias: 'Stockholm',
    lemma: 'Sweden',
  },
  { code: 'CHE', value: 'Switzerland', alias: '', lemma: 'Switzerland' },
  {
    code: 'CHE',
    value: 'Switzerland (Geneva)',
    alias: 'Geneva',
    lemma: 'Switzerland',
  },
  {
    code: 'CHE',
    value: 'Switzerland (Zurich)',
    alias: 'Zurich',
    lemma: 'Switzerland',
  },
  {
    code: 'SYR',
    value: 'Syrian Arab Republic',
    alias: '',
    lemma: 'Syrian Arab Republic',
  },
  { code: 'TWN', value: 'Taiwan', alias: '', lemma: 'Taiwan' },
  { code: 'TWN', value: 'Taiwan (Taipei)', alias: 'Taipei', lemma: 'Taiwan' },
  { code: 'TJK', value: 'Tajikistan', alias: '', lemma: 'Tajikistan' },
  {
    code: 'TZA',
    value: 'Tanzania, United Republic of',
    alias: '',
    lemma: 'Tanzania, United Republic of',
  },
  { code: 'THA', value: 'Thailand', alias: '', lemma: 'Thailand' },
  {
    code: 'THA',
    value: 'Thailand (Bangkok)',
    alias: 'Bangkok',
    lemma: 'Thailand',
  },
  {
    code: 'THA',
    value: 'Thailand (Chiang Mai)',
    alias: 'Chiang Mai',
    lemma: 'Thailand',
  },
  {
    code: 'THA',
    value: 'Thailand (Pattaya)',
    alias: 'Pattaya',
    lemma: 'Thailand',
  },
  {
    code: 'THA',
    value: 'Thailand (Phi Phi Island)',
    alias: 'Phi Phi Island',
    lemma: 'Thailand',
  },
  {
    code: 'THA',
    value: 'Thailand (Phuket)',
    alias: 'Phuket',
    lemma: 'Thailand',
  },
  { code: 'TLS', value: 'Timor-Leste', alias: '', lemma: 'Timor-Leste' },
  {
    code: 'TLS',
    value: 'Timor-Leste (East Timor)',
    alias: 'East Timor',
    lemma: 'Timor-Leste',
  },
  { code: 'TGO', value: 'Togo', alias: '', lemma: 'Togo' },
  { code: 'TKL', value: 'Tokelau', alias: '', lemma: 'Tokelau' },
  { code: 'TON', value: 'Tonga', alias: '', lemma: 'Tonga' },
  {
    code: 'TTO',
    value: 'Trinidad and Tobago',
    alias: '',
    lemma: 'Trinidad and Tobago',
  },
  { code: 'TUN', value: 'Tunisia', alias: '', lemma: 'Tunisia' },
  { code: 'TUR', value: 'Turkey', alias: '', lemma: 'Turkey' },
  { code: 'TUR', value: 'Turkey (Ankara)', alias: 'Ankara', lemma: 'Turkey' },
  { code: 'TUR', value: 'Turkey (Antalya)', alias: 'Antalya', lemma: 'Turkey' },
  {
    code: 'TUR',
    value: 'Turkey (Istanbul)',
    alias: 'Istanbul',
    lemma: 'Turkey',
  },
  { code: 'TKM', value: 'Turkmenistan', alias: '', lemma: 'Turkmenistan' },
  {
    code: 'TCA',
    value: 'Turks and Caicos Islands',
    alias: '',
    lemma: 'Turks and Caicos Islands',
  },
  { code: 'TUV', value: 'Tuvalu', alias: '', lemma: 'Tuvalu' },
  {
    code: 'VIR',
    value: 'U.S. Virgin Islands',
    alias: '',
    lemma: 'U.S. Virgin Islands',
  },
  {
    code: 'VIR',
    value: 'U.S. Virgin Islands (Saint Croix)',
    alias: 'Saint Croix',
    lemma: 'U.S. Virgin Islands',
  },
  {
    code: 'VIR',
    value: 'U.S. Virgin Islands (Saint John)',
    alias: 'Saint John',
    lemma: 'U.S. Virgin Islands',
  },
  {
    code: 'VIR',
    value: 'U.S. Virgin Islands (Saint Thomas)',
    alias: 'Saint Thomas',
    lemma: 'U.S. Virgin Islands',
  },
  {
    code: 'VIR',
    value: 'U.S. Virgin Islands (St Croix)',
    alias: 'St Croix',
    lemma: 'U.S. Virgin Islands',
  },
  {
    code: 'VIR',
    value: 'U.S. Virgin Islands (St John)',
    alias: 'St John',
    lemma: 'U.S. Virgin Islands',
  },
  {
    code: 'VIR',
    value: 'U.S. Virgin Islands (St Thomas)',
    alias: 'St Thomas',
    lemma: 'U.S. Virgin Islands',
  },
  {
    code: 'VIR',
    value: 'U.S. Virgin Islands (St. Croix)',
    alias: 'St. Croix',
    lemma: 'U.S. Virgin Islands',
  },
  {
    code: 'VIR',
    value: 'U.S. Virgin Islands (St. John)',
    alias: 'St. John',
    lemma: 'U.S. Virgin Islands',
  },
  {
    code: 'VIR',
    value: 'U.S. Virgin Islands (St. Thomas)',
    alias: 'St. Thomas',
    lemma: 'U.S. Virgin Islands',
  },
  {
    code: 'VIR',
    value: 'U.S. Virgin Islands (US Virgin Islands)',
    alias: 'US Virgin Islands',
    lemma: 'U.S. Virgin Islands',
  },
  { code: 'UGA', value: 'Uganda', alias: '', lemma: 'Uganda' },
  { code: 'UKR', value: 'Ukraine', alias: '', lemma: 'Ukraine' },
  { code: 'UKR', value: 'Ukraine (Kiev)', alias: 'Kiev', lemma: 'Ukraine' },
  {
    code: 'ARE',
    value: 'United Arab Emirates',
    alias: '',
    lemma: 'United Arab Emirates',
  },
  {
    code: 'ARE',
    value: 'United Arab Emirates (Abu Dhabi)',
    alias: 'Abu Dhabi',
    lemma: 'United Arab Emirates',
  },
  {
    code: 'ARE',
    value: 'United Arab Emirates (Dubai)',
    alias: 'Dubai',
    lemma: 'United Arab Emirates',
  },
  {
    code: 'ARE',
    value: 'United Arab Emirates (UAE)',
    alias: 'UAE',
    lemma: 'United Arab Emirates',
  },
  { code: 'GBR', value: 'United Kingdom', alias: '', lemma: 'United Kingdom' },
  {
    code: 'GBR',
    value: 'United Kingdom (Bath)',
    alias: 'Bath',
    lemma: 'United Kingdom',
  },
  {
    code: 'GBR',
    value: 'United Kingdom (Birmingham)',
    alias: 'Birmingham',
    lemma: 'United Kingdom',
  },
  {
    code: 'GBR',
    value: 'United Kingdom (Bristol)',
    alias: 'Bristol',
    lemma: 'United Kingdom',
  },
  {
    code: 'GBR',
    value: 'United Kingdom (Cardiff)',
    alias: 'Cardiff',
    lemma: 'United Kingdom',
  },
  {
    code: 'GBR',
    value: 'United Kingdom (Edinburgh)',
    alias: 'Edinburgh',
    lemma: 'United Kingdom',
  },
  {
    code: 'GBR',
    value: 'United Kingdom (England)',
    alias: 'England',
    lemma: 'United Kingdom',
  },
  {
    code: 'GBR',
    value: 'United Kingdom (Glasgow)',
    alias: 'Glasgow',
    lemma: 'United Kingdom',
  },
  {
    code: 'GBR',
    value: 'United Kingdom (Great Britain)',
    alias: 'Great Britain',
    lemma: 'United Kingdom',
  },
  {
    code: 'GBR',
    value: 'United Kingdom (Liverpool)',
    alias: 'Liverpool',
    lemma: 'United Kingdom',
  },
  {
    code: 'GBR',
    value: 'United Kingdom (London)',
    alias: 'London',
    lemma: 'United Kingdom',
  },
  {
    code: 'GBR',
    value: 'United Kingdom (Manchester)',
    alias: 'Manchester',
    lemma: 'United Kingdom',
  },
  {
    code: 'GBR',
    value: 'United Kingdom (Northern Ireland)',
    alias: 'Northern Ireland',
    lemma: 'United Kingdom',
  },
  {
    code: 'GBR',
    value: 'United Kingdom (Scotland)',
    alias: 'Scotland',
    lemma: 'United Kingdom',
  },
  {
    code: 'GBR',
    value: 'United Kingdom (Shetland Islands)',
    alias: 'Shetland Islands',
    lemma: 'United Kingdom',
  },
  {
    code: 'GBR',
    value: 'United Kingdom (UK)',
    alias: 'UK',
    lemma: 'United Kingdom',
  },
  {
    code: 'GBR',
    value: 'United Kingdom (Wales)',
    alias: 'Wales',
    lemma: 'United Kingdom',
  },
  { code: 'USA', value: 'United States', alias: '', lemma: 'United States' },
  {
    code: 'USA',
    value: 'United States (Alabama)',
    alias: 'Alabama',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Anaheim)',
    alias: 'Anaheim',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Arizona)',
    alias: 'Arizona',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Arkansas)',
    alias: 'Arkansas',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Asheville)',
    alias: 'Asheville',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Aspen)',
    alias: 'Aspen',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Atlanta)',
    alias: 'Atlanta',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Austin)',
    alias: 'Austin',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Baltimore)',
    alias: 'Baltimore',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Boston)',
    alias: 'Boston',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Branson)',
    alias: 'Branson',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (California)',
    alias: 'California',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Charleston)',
    alias: 'Charleston',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Charlotte)',
    alias: 'Charlotte',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Chicago)',
    alias: 'Chicago',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Colorado)',
    alias: 'Colorado',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Connecticut)',
    alias: 'Connecticut',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Dallas)',
    alias: 'Dallas',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Delaware)',
    alias: 'Delaware',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Denver)',
    alias: 'Denver',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Detroit)',
    alias: 'Detroit',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Florida)',
    alias: 'Florida',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Fort Lauderdale)',
    alias: 'Fort Lauderdale',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Georgia)',
    alias: 'Georgia',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Houston)',
    alias: 'Houston',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Idaho)',
    alias: 'Idaho',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Illinois)',
    alias: 'Illinois',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Indiana)',
    alias: 'Indiana',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Indianapolis)',
    alias: 'Indianapolis',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Iowa)',
    alias: 'Iowa',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Jacksonville)',
    alias: 'Jacksonville',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Kansas City)',
    alias: 'Kansas City',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Kansas)',
    alias: 'Kansas',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Kentucky)',
    alias: 'Kentucky',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Key West)',
    alias: 'Key West',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Las Vegas)',
    alias: 'Las Vegas',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Los Angeles)',
    alias: 'Los Angeles',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Louisiana)',
    alias: 'Louisiana',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Maine)',
    alias: 'Maine',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Maryland)',
    alias: 'Maryland',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Massachusetts)',
    alias: 'Massachusetts',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Miami)',
    alias: 'Miami',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Miami)',
    alias: 'Miami',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Michigan)',
    alias: 'Michigan',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Minneapolis)',
    alias: 'Minneapolis',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Minnesota)',
    alias: 'Minnesota',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Mississippi)',
    alias: 'Mississippi',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Missouri)',
    alias: 'Missouri',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Moab)',
    alias: 'Moab',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Montana)',
    alias: 'Montana',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Napa)',
    alias: 'Napa',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Nashville)',
    alias: 'Nashville',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Nebraska)',
    alias: 'Nebraska',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Nevada)',
    alias: 'Nevada',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (New Hampshire)',
    alias: 'New Hampshire',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (New Jersey)',
    alias: 'New Jersey',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (New Mexico)',
    alias: 'New Mexico',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (New Orleans)',
    alias: 'New Orleans',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (New York City)',
    alias: 'New York City',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (New York)',
    alias: 'New York',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Niagara Falls)',
    alias: 'Niagara Falls',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (North Carolina)',
    alias: 'North Carolina',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (North Dakota)',
    alias: 'North Dakota',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Ohio)',
    alias: 'Ohio',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Oklahoma)',
    alias: 'Oklahoma',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Oregon)',
    alias: 'Oregon',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Orlando)',
    alias: 'Orlando',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Pennsylvania)',
    alias: 'Pennsylvania',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Philadelphia)',
    alias: 'Philadelphia',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Phoenix)',
    alias: 'Phoenix',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Rhode Island)',
    alias: 'Rhode Island',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Saint Louis)',
    alias: 'Saint Louis',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (San Antonio)',
    alias: 'San Antonio',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (San Diego)',
    alias: 'San Diego',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (San Francisco)',
    alias: 'San Francisco',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Savannah)',
    alias: 'Savannah',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Seattle)',
    alias: 'Seattle',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Sedona)',
    alias: 'Sedona',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (South Carolina)',
    alias: 'South Carolina',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (South Dakota)',
    alias: 'South Dakota',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (St Louis)',
    alias: 'St Louis',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (St. Louis)',
    alias: 'St. Louis',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Tampa)',
    alias: 'Tampa',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Tennessee)',
    alias: 'Tennessee',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Texas)',
    alias: 'Texas',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (United States of America)',
    alias: 'United States of America',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Utah)',
    alias: 'Utah',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Vermont)',
    alias: 'Vermont',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Virginia)',
    alias: 'Virginia',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Washington)',
    alias: 'Washington',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Washington, D.C.)',
    alias: 'Washington, D.C.',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (West Virginia)',
    alias: 'West Virginia',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Wisconsin)',
    alias: 'Wisconsin',
    lemma: 'United States',
  },
  {
    code: 'USA',
    value: 'United States (Wyoming)',
    alias: 'Wyoming',
    lemma: 'United States',
  },
  {
    code: 'AK',
    value: 'United States - Alaska',
    alias: '',
    lemma: 'United States - Alaska',
  },
  {
    code: 'USA',
    value: 'United States - Continental',
    alias: '',
    lemma: 'United States - Continental',
  },
  {
    code: 'HI',
    value: 'United States - Hawaii',
    alias: '',
    lemma: 'United States - Hawaii',
  },
  {
    code: 'HI',
    value: 'United States - Hawaii (Honolulu)',
    alias: 'Honolulu',
    lemma: 'United States - Hawaii',
  },
  {
    code: 'UMI',
    value: 'United States Minor Outlying Islands',
    alias: '',
    lemma: 'United States Minor Outlying Islands',
  },
  { code: 'URY', value: 'Uruguay', alias: '', lemma: 'Uruguay' },
  { code: 'UZB', value: 'Uzbekistan', alias: '', lemma: 'Uzbekistan' },
  { code: 'VUT', value: 'Vanuatu', alias: '', lemma: 'Vanuatu' },
  {
    code: 'VUT',
    value: 'Vanuatu (Mystery Island)',
    alias: 'Mystery Island',
    lemma: 'Vanuatu',
  },
  {
    code: 'VUT',
    value: 'Vanuatu (Port Vila)',
    alias: 'Port Vila',
    lemma: 'Vanuatu',
  },
  { code: 'VEN', value: 'Venezuela', alias: '', lemma: 'Venezuela' },
  {
    code: 'VEN',
    value: 'Venezuela (Caracas)',
    alias: 'Caracas',
    lemma: 'Venezuela',
  },
  { code: 'VNM', value: 'Vietnam', alias: '', lemma: 'Vietnam' },
  { code: 'VNM', value: 'Vietnam (Hanoi)', alias: 'Hanoi', lemma: 'Vietnam' },
  {
    code: 'VNM',
    value: 'Vietnam (Ho Chi Minh City)',
    alias: 'Ho Chi Minh City',
    lemma: 'Vietnam',
  },
  {
    code: 'WLF',
    value: 'Wallis and Futuna',
    alias: '',
    lemma: 'Wallis and Futuna',
  },
  { code: 'ESH', value: 'Western Sahara', alias: '', lemma: 'Western Sahara' },
  { code: 'YEM', value: 'Yemen', alias: '', lemma: 'Yemen' },
  { code: 'ZMB', value: 'Zambia', alias: '', lemma: 'Zambia' },
  { code: 'ZWE', value: 'Zimbabwe', alias: '', lemma: 'Zimbabwe' },
  { code: 'SWZ', value: 'eSwatini', alias: '', lemma: 'eSwatini' },
  {
    code: 'SWZ',
    value: 'eSwatini (Swaziland)',
    alias: 'Swaziland',
    lemma: 'eSwatini',
  },
];
